<?php

require_once "Framework/Controller.php";

/**
 * Class ControllerAdmin
 */
abstract class ControllerRh extends Controller
{

    public function executeAction($action)
    {


        if($this->session->getAttribute("user")["statut"] !== '3') {

            parent::executeAction($action);
        } else {
            parent::redirect('home');
        }
    }

    public function disconnect()
    {
        parent::disconnect(); // TODO: Change the autogenerated stub
    }
}