<?php

require_once "Framework/Controller.php";

/**
 * Class ControllerAdmin
 */
abstract class ControllerAdmin extends Controller
{

    /**
     * Je tente d'expliquer que cette fonction execute une action
     *
     * @param $action
     * @author Arthur Cann <arthur.cann@isep.fr>
     * @throws Exception
     */
    public function executeAction($action)
    {
        if($this->request->getSession()->getAttribute("statut") == 1) {
            parent::executeAction($action);
        } else {
            parent::redirect('Home');
        }

    }

    public function disconnect()
    {
        parent::disconnect(); // TODO: Change the autogenerated stub
    }
}