<?php

require_once 'ControllerAdmin.php';

class ControllerAdminhome extends ControllerAdmin
{
    public function index() {
        $this->generateView(array("pseudo" => $this->request->getSession()->getAttribute("user")['statut']));
    }

    public function register() {
        $this->redirect("register");
    }

    public function disconnect()
    {
        parent::disconnect(); // TODO: Change the autogenerated stub
    }
}